from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True, slots=True)
class LanguageOption:
    id: str
    label: str
    lang: str | None
    tld: str | None
    supported: bool
    note: str

    def to_dict(self) -> dict[str, str | bool | None]:
        return asdict(self)


LANGUAGE_OPTIONS = [
    LanguageOption(
        id="english-uk",
        label="English UK",
        lang="en",
        tld="co.uk",
        supported=True,
        note="Routes English speech through Google United Kingdom for a British accent.",
    ),
    LanguageOption(
        id="english-us",
        label="English US",
        lang="en",
        tld="com",
        supported=True,
        note="Uses Google's default English voice, which is the closest gTTS match for US English.",
    ),
    LanguageOption(
        id="english-sa",
        label="English SA",
        lang="en",
        tld="co.za",
        supported=True,
        note="Routes English speech through Google South Africa for a South African accent.",
    ),
    LanguageOption(
        id="afrikaans",
        label="Afrikaans",
        lang="af",
        tld="com",
        supported=True,
        note="Standard Afrikaans voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="arabic",
        label="Arabic",
        lang="ar",
        tld="com",
        supported=True,
        note="Standard Arabic voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="bengali",
        label="Bengali",
        lang="bn",
        tld="com",
        supported=True,
        note="Standard Bengali voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="chinese-simplified",
        label="Chinese (Simplified)",
        lang="zh-CN",
        tld="com",
        supported=True,
        note="Mandarin speech using the Simplified Chinese voice in gTTS.",
    ),
    LanguageOption(
        id="chinese-traditional",
        label="Chinese (Traditional)",
        lang="zh-TW",
        tld="com",
        supported=True,
        note="Mandarin speech using the Traditional Chinese voice in gTTS.",
    ),
    LanguageOption(
        id="dutch",
        label="Dutch",
        lang="nl",
        tld="com",
        supported=True,
        note="Standard Dutch voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="french",
        label="French",
        lang="fr",
        tld="com",
        supported=True,
        note="Standard French voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="german",
        label="German",
        lang="de",
        tld="com",
        supported=True,
        note="Standard German voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="greek",
        label="Greek",
        lang="el",
        tld="com",
        supported=True,
        note="Standard Greek voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="gujarati",
        label="Gujarati",
        lang="gu",
        tld="com",
        supported=True,
        note="Standard Gujarati voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="hausa",
        label="Hausa",
        lang="ha",
        tld="com",
        supported=True,
        note="Standard Hausa voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="hindi",
        label="Hindi",
        lang="hi",
        tld="com",
        supported=True,
        note="Standard Hindi voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="igbo",
        label="Igbo",
        lang=None,
        tld=None,
        supported=False,
        note="Igbo is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="indonesian",
        label="Indonesian",
        lang="id",
        tld="com",
        supported=True,
        note="Standard Indonesian voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="italian",
        label="Italian",
        lang="it",
        tld="com",
        supported=True,
        note="Standard Italian voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="japanese",
        label="Japanese",
        lang="ja",
        tld="com",
        supported=True,
        note="Standard Japanese voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="korean",
        label="Korean",
        lang="ko",
        tld="com",
        supported=True,
        note="Standard Korean voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="portuguese",
        label="Portuguese",
        lang="pt",
        tld="com",
        supported=True,
        note="Uses the Brazilian Portuguese voice exposed by gTTS.",
    ),
    LanguageOption(
        id="sepedi",
        label="Sepedi",
        lang=None,
        tld=None,
        supported=False,
        note="Sepedi is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="russian",
        label="Russian",
        lang="ru",
        tld="com",
        supported=True,
        note="Standard Russian voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="spanish",
        label="Spanish",
        lang="es",
        tld="com",
        supported=True,
        note="Standard Spanish voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="sotho",
        label="Sotho",
        lang=None,
        tld=None,
        supported=False,
        note="Sotho is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="southern-ndebele",
        label="Southern Ndebele",
        lang=None,
        tld=None,
        supported=False,
        note="Southern Ndebele is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="swahili",
        label="Swahili",
        lang="sw",
        tld="com",
        supported=True,
        note="Standard Swahili voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="swazi",
        label="Swazi",
        lang=None,
        tld=None,
        supported=False,
        note="Swazi is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="turkish",
        label="Turkish",
        lang="tr",
        tld="com",
        supported=True,
        note="Standard Turkish voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="tsonga",
        label="Tsonga",
        lang=None,
        tld=None,
        supported=False,
        note="Tsonga is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="tswana",
        label="Tswana",
        lang=None,
        tld=None,
        supported=False,
        note="Tswana is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="ukrainian",
        label="Ukrainian",
        lang="uk",
        tld="com",
        supported=True,
        note="Standard Ukrainian voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="urdu",
        label="Urdu",
        lang="ur",
        tld="com",
        supported=True,
        note="Standard Urdu voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="venda",
        label="Venda",
        lang=None,
        tld=None,
        supported=False,
        note="Venda is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="vietnamese",
        label="Vietnamese",
        lang="vi",
        tld="com",
        supported=True,
        note="Standard Vietnamese voice from Google Text-to-Speech.",
    ),
    LanguageOption(
        id="xhosa",
        label="Xhosa",
        lang=None,
        tld=None,
        supported=False,
        note="Xhosa is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="yoruba",
        label="Yoruba",
        lang=None,
        tld=None,
        supported=False,
        note="Yoruba is not currently available in the installed gTTS language set.",
    ),
    LanguageOption(
        id="zulu",
        label="Zulu",
        lang=None,
        tld=None,
        supported=False,
        note="Zulu is not currently available in the installed gTTS language set.",
    ),
]

LANGUAGE_PAYLOAD = [option.to_dict() for option in LANGUAGE_OPTIONS]
SUPPORTED_LANGUAGE_OPTIONS = [option.to_dict() for option in LANGUAGE_OPTIONS if option.supported]
UNSUPPORTED_LANGUAGE_OPTIONS = [option.to_dict() for option in LANGUAGE_OPTIONS if not option.supported]
LANGUAGE_OPTIONS_BY_ID = {option["id"]: option for option in LANGUAGE_PAYLOAD}
